config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'archive_items/index'
      get '/archive_items/:id', to: 'archive_items#show'
    end
  end

  resources :archive_items
  get 'archive_items/index'
  get 'archive_items/create'
  get 'archive_items/show'
  get 'archive_items/new'
  get 'archive_items/edit'
  get 'archive_items/destroy'

  root 'homepage#index'
  get '/*path' => 'homepage#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive_item.rb
class ArchiveItem < ApplicationRecord
end

app/controllers/api/v1/archive_items_controller.rb
class Api::V1::ArchiveItemsController < ApplicationController
  def index
    archive_items = ArchiveItem.all.order(created_at: :desc)
    render json: archive_items
  end

  def show
    if archive_item
      render json: archive_item
    else
      render json: archive_item.errors
    end
  end

  private 
  
  def archive_item
    @archive_item ||= ArchiveItem.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archive_items_controller.rb
class ArchiveItemsController < ApplicationController
  def index
    @archive_items = ArchiveItem.all.order(created_at: :desc)
  end

  def new
    @archive_item = ArchiveItem.new
  end  

  def create
    archive_item = ArchiveItem.create(archive_item_params)
    redirect_to archive_items_path
  end

  def show    
    @archive_item = ArchiveItem.find(params[:id])
  end

  def edit
    @archive_item = ArchiveItem.find(params[:id])
  end

  def update
    @archive_item = ArchiveItem.find(params[:id])
    @archive_item.update(archive_item_params)

    redirect_to archive_item_path(@archive_item)
  end

  def destroy
    @archive_item = ArchiveItem.find(params[:id])
    @archive_item.destroy

    redirect_to archive_items_path
  end

  private

  def archive_item_params
    params.require(:archive_item).permit(:title, :medium, :year, :credit, :location)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/archive_items/create.html.erb
<h1>Api::V1::ArchiveItems#create</h1>
<p>Find me in app/views/api/v1/archive_items/create.html.erb</p>

app/views/archive_items/destroy.html.erb
<h1>Api::V1::ArchiveItems#destroy</h1>
<p>Find me in app/views/api/v1/archive_items/destroy.html.erb</p>

app/views/archive_items/edit.html.erb
<h3>Update Archive Item</h3>
<%= form_with model: @archive_item do |form| %>
  <%= form.text_field :title, placeholder: "Title" %>
  <%= form.text_field :medium, placeholder: "Medium" %>
  <%= form.text_field :year, placeholder: "Year" %>
  <%= form.text_field :location, placeholder: "Location" %>
  <%= form.text_field :credit, placeholder: "Credit" %>
  <%= form.submit %>
<% end %>

app/views/archive_items/index.html.erb
<h1>Archive Items Index</h1>

<table>
  <% @archive_items.each do |archive_item| %>
    <tr>
      <td><%= link_to archive_item.title, archive_item_path(archive_item) %></td>
      <td><%= button_to 'Edit', edit_archive_item_path(archive_item), method: 'get'%></td>
      <td><%= button_to 'Remove', archive_item_path(archive_item), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to "Add Archive Item", new_archive_item_path %>

app/views/archive_items/new.html.erb
<h3>Create an Item</h3>
<%= form_with model: @archive_item do |form| %>
  <%= form.text_field :title, placeholder: "Title" %>
  <%= form.text_field :medium, placeholder: "Medium" %>
  <%= form.text_field :year, placeholder: "Year" %>
  <%= form.text_field :location, placeholder: "Location" %>
  <%= form.text_field :credit, placeholder: "Credit" %>
  <%= form.submit %>
<% end %>

app/views/archive_items/show.html.erb
<h1><%= @archive_item.title %></h1>
<p>Medium: <%= @archive_item.medium %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>World Arts Foundation Inc.</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= javascript_pack_tag 'Index' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Newsreader&family=Poppins:ital,wght@0,300;0,400;0,500;0,700;1,400&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>